# exemplo em https://raw.github.com/travis-ci/travis-ci-php-example/master/.travis.yml
# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  # using major version aliases

  # aliased to a recent 5.3.x version
  - 5.3
  # aliased to a recent 5.4.x version
  - 5.4
  # aliased to a recent 5.5.x version
  - 5.5

#services:
#  - redis-server
#  - memcached
#  - elasticsearch
#  - mongodb

# optionally specify a list of environments, for example to test different RDBMS
#env:
#  - DB=pgsql
  
install:
  - composer self-update && composer --version
  - composer install --dev -v

# execute any number of scripts before the test run, custom env's are available as variables
#before_script:
#  - if [[ "$DB" == "pgsql" ]]; then psql -c "DROP DATABASE IF EXISTS hello_world_test;" -U postgres; fi
#  - if [[ "$DB" == "pgsql" ]]; then psql -c "create database hello_world_test;" -U postgres; fi

# omitting "script:" will default to phpunit
# use the $DB env variable to determine the phpunit.xml to use
script: 
  bin/phpunit --verbose --configuration phpunit.xml.dist

# configure notifications (email, IRC, campfire etc)
#notifications:
#  irc: "irc.freenode.org#travis"